### ISSUE TITLE
https

### ISSUE THREAD

**Issue by fyears** [cosname/R-conference#14]
现在 github 自定义域名也支持 https 了。所以这里应该也可以设置。我没有权限访问这个 repo 的 setting，你们来吧。

@yihui @Lchiffon

**Comment by yihui** [comment]
china-r.org 也不在我手里。

@yixuan 能处理一下吗？

![image](https://user-images.githubusercontent.com/163582/43679653-3adda6bc-97ee-11e8-8541-59a1fa2a2395.png)

**Comment by fyears** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

嗯，需要域名那边做 a record

**Comment by yihui** [comment]
要是 @lijian13 没有看邮件的话，就微信告知一下吧。

**Comment by yixuan** [comment]
嗯，我之前发的邮箱他已经不用了，刚转发了新的。大概明天处理。

**Comment by yixuan** [comment]
拖了好久，终于搞定了。

**Comment by yihui** [comment]
才不到一年，不算太久 😂
