### ISSUE TITLE
china-r.org 被抢注了吗？

### ISSUE THREAD

**Issue by CyrusYip** [cosname/R-conference#24]
http://china-r.org/

https://web.archive.org/web/20230124165137/https://china-r.org/

现在页面显示售价 15988。

<img width="503" alt="image" src="https://user-images.githubusercontent.com/60951091/215362758-e048fb7e-2be1-4de5-b9cf-e43882d2c4ac.png">

**Comment by CyrusYip** [comment]
在统计之都论坛发了帖子：<https://d.cosx.org/d/423918-china-rorg-bei-qiang-zhu-liao-ma>

**Comment by dddd1007** [comment]
> 

已反馈，谢谢提醒！

**Comment by CyrusYip** [comment]
现在已经改到 https://china-r.cosx.org/ 了，但本仓库的关于信息还没改好。

<img width="113" alt="image" src="https://user-images.githubusercontent.com/60951091/225044296-2afb0e5f-18ef-4af6-a1a8-5efb9c759933.png">
